### ISSUE TITLE
linux-arm target generates x64 installer

### ISSUE THREAD

**Issue by dmitry-demchuk** [qmfrederik/dotnet-packaging#117] opened 2019-09-25 08:05 UTC
Both, linux-arm and linux-arm64 targets generate 64 bit installer.

pi@raspberrypi:/tmp $ sudo dpkg -i capp.1.0.0.linux-arm.deb 
dpkg: error processing archive capp.1.0.0.linux-arm.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 capp.1.0.0.linux-arm.deb

**Comment by claunia** [comment] 2019-09-26 07:52
Duplicate of #51

**Closed** 2019-11-21 13:09 UTC
