### ISSUE TITLE
Error MSB4057: The target "CreateDeb" does not exist in the project.

### ISSUE THREAD

**Issue by endasil** [qmfrederik/dotnet-packaging#97] opened 2019-05-04 09:53 UTC
I saw the response to the other post and have made sure i have <PackageReference Include="Packaging.Targets" Version="0.1.56" /> entry under ItemGroups . Is there something i missed in the readme?  
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>	
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <RootNamespace>myprogram</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseDatabase.net" Version="4.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.2.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    <PackageReference Include="RabbitMQ.Client" Version="5.1.0" />
	<PackageReference Include="Packaging.Targets" Version="0.1.56" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>

```

**Comment by maikebing** [comment] 2019-05-19 17:36
I had the same problem on Appveyor. 
https://ci.appveyor.com/project/MaiKeBing/iotsharp

**Comment by buckstephenh** [comment] 2019-05-24 18:38
Same issue.  Mine is in a related test project that the .sln file references.  Still appears to work at first blush.

**Comment by budul100** [comment] 2019-06-12 15:33
It seems that you have to run firstly the respective` dotnet publish` command and then the `dotnet deb` command. I had the same error, but after using ` dotnet publish` it worked correctly.

**Comment by qmfrederik** [comment] 2019-06-16 20:26
This can happen if you did not run `dotnet restore` first (you shouldn't need to run `dotnet publish`).

Can you check whether this problem reproduces on a clean checkout, and that running `dotnet restore` fixes this?

**Comment by qmfrederik** [comment] 2019-06-16 20:26
Duplicate of #90, by the way.

**Comment by qmfrederik** [comment] 2019-11-22 16:14
This should have been fixed with the latest versions, this should now just work:

```bash
dotnet new console
dotnet tool install --global dotnet-deb
dotnet deb install
dotnet deb
```

Please reopen if you still have this issue with the latest versions.

**Closed by qmfrederik** 2019-11-22 16:14 UTC
